---
# Local Vagrant options.
vagrant_hostname: local.drupalvm.com
vagrant_machine_name: local-drupalvm
vagrant_ip: 192.168.88.10

# Composer project settings.
drupal_build_composer_project: false
drupal_build_composer: true
drupal_composer_path: false
drupal_composer_install_dir: "/var/www/drupalvm"
drupal_core_path: "{{ drupal_composer_install_dir }}/web"
drupal_composer_dependencies: []
drupal_enable_modules:
  - admin_toolbar
  - pathauto
  - redirect

# Other overrides.
php_version: "7.1"
installed_extras:
  - drush
  - mailhog
  - varnish
