---
drupal_deploy: true
drupal_deploy_repo: "git@github.com:geerlingguy/drupalvm-live.git"
drupal_deploy_dir: /var/www/drupal

drupal_domain: "prod.drupalvm.com"
vagrant_hostname: "{{ drupal_domain }}"

apache_vhosts:
  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
